@startuml parti-prenantes
left to right direction
:chargerLaboratoire: --> (Correction)
:coordonnateur:--> (allo)
:equipe: --> (aa)

@enduml
<!-------------------------------->

@startuml proposition

Actor ChargéDeLaboratoire
Actor TesteurSystem 

interface IDataReader
interface IExternalService
interface IRouteComparator
interface IServiceDiscovery
interface IServiceRegister

component ChaosMonkey <<Microservice avec UI>>
component ExternalServices <<Microservice>>
component GpsAppSimulator <<Microservice avec UI>>
component ServerSimulation <<Microservice>>
component ServerSwitch <<Microservice avec UI>>
component PerturbateurDeTraffic <<Microservice avec UI>>
component RouteComparatorApp <<Microservice avec UI>>
component RouteComparatorService <<Microservice>>
component ServiceDiscovery <<Microservice>>
component TimeTravelCalculator <<Microservice>>
component TrafficMonitoring<<Microservice avec UI>>

note bottom of ExternalServices: Un seul service externe par équipeÉ\nChaque équipe doit utiliser un service différent.  
note bottom of IServiceRegister: Tous les microservices s'enregistrent\nà l'aide de cette interface


PerturbateurDeTraffic -- ServerSimulation: perturbe


ExternalServices .u.|> IExternalService

ServiceDiscovery .d.|> IServiceRegister
ServiceDiscovery .u.|> IServiceDiscovery
ChaosMonkey --> IServiceDiscovery 
ChargéDeLaboratoire --> PerturbateurDeTraffic
ChargéDeLaboratoire --> ChaosMonkey  : Utilise et configure
ChargéDeLaboratoire --> ServerSwitch  :switch data source
ChargéDeLaboratoire --> RouteComparatorApp  : Utilise et configure
ChargéDeLaboratoire --> TrafficMonitoring: Observe
GpsAppSimulator -d-> IRouteComparator
ServerSimulation .u.|> IDataReader
ServerSwitch  ..|> IDataReader
ServerSwitch --> IDataReader
RouteComparatorApp --> IRouteComparator
TimeTravelCalculator <-- IDataReader
TimeTravelCalculator -u-> TrafficMonitoring
RouteComparatorService -u-> TrafficMonitoring
RouteComparatorService --> IExternalService
RouteComparatorService --> IServiceDiscovery
RouteComparatorService .u.|> IRouteComparator
TesteurSystem  --> GpsAppSimulator: utilise et configure 

@enduml

