@startuml

node "Docker Desktop" {
    component TripComparator as tc
    component RouteTimeProvider as rtp
    component Stm
    queue RabbitMQ as mq
}
mq <..> tc : AMQP protocol
tc -(0-> rtp : Get
tc -(0-> Stm : Get/Post

component Stm_Api
component TomTom_Api

Stm -(0-> Stm_Api : Get
rtp -(0-> TomTom_Api : Get

@enduml