@startuml

node "Portainer chargés de laboratoire" {
    component UI as ui #LightSkyBlue
    component Ingress as ingress #LightSkyBlue
    component AuthService as auth #LightSkyBlue
    Database InfluxDB as influx #LightSkyBlue
    Database Postgres as sql #LightSkyBlue
    component Adminer as admin #LightSkyBlue
    queue RabbitMQ as portainerMq #LightSkyBlue
}

node "Docker Desktop"{
    component NodeController as nodeC #LightSkyBlue 
    component TripComparator as tc #Gold
    component RouteTimeProvider as rtp #Gold
    component Stm #Gold
    queue RabbitMQ as mq {
        card "coordinate_message(exchange)" as queryEx #LightSkyBlue 
        card "bus_position_updated(exchange)" as resEx #Gold
        queue query as qq #Gold
        queue response as rq #LightSkyBlue 
        queryEx --> qq
        rq <-- resEx
    }
}

ui -(0-> ingress : Get/Post
ingress -(0-> auth : Get/Post
admin --> sql
ingress --->  influx : Read
ingress <...> portainerMq : AMQP protocol
portainerMq <..> nodeC : AMQP protocol
ingress <---0)--- nodeC : Get/Post
influx <--- nodeC : Write
auth -->  sql : Read/Write
nodeC ..> queryEx : AMQP protocol
nodeC <.. rq : AMQP protocol
qq ..> tc : AMQP protocol
resEx <.. tc : AMQP protocol
tc -(0-> rtp : Get
tc -(0-> Stm : Get/Post

component Stm_Api #White
component TomTom_Api #White

Stm -(0-> Stm_Api : Get
rtp -(0-> TomTom_Api : Get

legend top
    | Color | Managed by |
    |<#LightSkyBlue>| ÉTS |
    |<#Gold>| Votre équipe |
    |<#White>| Service Externes |
endlegend

@enduml