@startuml

node "Docker Desktop" {
    component NodeController as nodeC #LightSkyBlue
    component TripComparator as tc #Gold
    component RouteTimeProvider as rtp #Gold
    component Stm #Gold
    queue RabbitMQ as mq {
        card "coordinate_message(exchange)" as queryEx #LightSkyBlue
        card "bus_position_updated(exchange)" as resEx #Gold
        queue query as qq #Gold
        queue response as rq #LightSkyBlue
        queryEx --> qq
        rq <-- resEx
    }
}

nodeC ..> queryEx : AMQP protocol
nodeC <.. rq : AMQP protocol
qq ..> tc : AMQP protocol
resEx <.. tc : AMQP protocol
tc -(0-> rtp : Get
tc -(0-> Stm : Get/Post

component Stm_Api #White
component TomTom_Api #White

Stm -(0-> Stm_Api : Get
rtp -(0-> TomTom_Api : Get

legend top
    | Color | Managed by |
    |<#LightSkyBlue>| ÉTS |
    |<#Gold>| Votre équipe |
    |<#White>| Service Externes |
endlegend

@enduml