//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] stop_times {
            get {
                object obj = ResourceManager.GetObject("stop_times", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_url,location_type,parent_station,wheelchair_boarding
        ///STATION_M118,10118,STATION ANGRIGNON,45.446466,-73.603118,,1,,1
        ///43,10118,Station Angrignon,45.446466,-73.603118,http://www.stm.info/fr/infos/reseaux/metro/angrignon,0,STATION_M118,1
        ///43-01,10118,Station Angrignon,45.446319,-73.603835,,2,STATION_M118,1
        ///STATION_M120,10120,STATION MONK,45.451158,-73.593242,,1,,2
        ///42,10120,Station Monk,45.451158,-73.593242,http://www.stm.info/fr/infos/reseaux/metro/monk,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stops {
            get {
                return ResourceManager.GetString("stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route_id,service_id,trip_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,note_fr,note_en
        ///5,23S-GLOBAUX-00-S,265937677,STATION SAINT-MICHEL,0,51763,1,,
        ///5,23S-GLOBAUX-00-S,265937682,STATION SNOWDON,1,51762,1,,
        ///5,23S-GLOBAUX-00-S,265937684,STATION SAINT-MICHEL,0,51763,1,,
        ///5,23S-GLOBAUX-00-S,265937687,STATION SNOWDON,1,51762,1,,
        ///5,23S-GLOBAUX-00-S,265937689,STATION SAINT-MICHEL,0,51763,1,,
        ///5,23S-GLOBAUX-00-S,265937695,STATION SAINT-MICHEL,0,51763,1,,
        ///5,23S-GLOBAUX-00-S,265937696,STATION SAIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trips {
            get {
                return ResourceManager.GetString("trips", resourceCulture);
            }
        }
    }
}
