@startuml
skinparam Style strictuml
participant "ctrl:ControleurAuthentification_UI" as ctrl
participant "Ipublic:ServiceTrajet" as Ipublic

note left of ctrl: Controleur de session
-> ctrl: ComparerTrajet(String: départ, String: arrivée, int:taux,String: nom)
note left of Ipublic: Expert qui dirige les requetes vers les autres microServices
ctrl -> Ipublic: liste:get(https://portainer.10.194.33.156.nip.io/components/schemas/TrajetArray) 
Ipublic -> ctrl: liste: tableau du temps de déplacement

-> ctrl: ComparerCourtTrajet(String: départ, String: arrivée ,String: nom)
ctrl -> Ipublic: trajet : get(https://portainer.10.194.33.156.nip.io/components/schemas/Trajet)
Ipublic -> ctrl:  trajet: "trajet le plus court"

@enduml