@startuml
skinparam Style strictuml
participant "ctrl:ControleurAuthentification_UI" as ctrl
participant "Ipublic:ServiceDiscovery" as Ipublic

note left of ctrl: Controleur de session
-> ctrl: Register(String: token)
note left of Ipublic: Expert qui dirige les requetes vers les autres microServices
ctrl -> Ipublic: reponse = Post(https://localhost/v1/components/schemas/Registration)
Ipublic -> ctrl: reponse = 200
-> ctrl: Discover(Sting :msRoute)
ctrl -> Ipublic: msRoute = get(https://localhost/v1/components/schemas/route)
Ipublic -> ctrl: msRoute = "route"

@enduml