@startuml RDTQ Sécurité : Résister aux attaques

actor ": Utilisateur" as user
participant ": Chaosmonkey" as chaos
participant ": Authentication service" as auth
participant "Service 1 : Microservice" as s1

note over user, s1 : Tactique : Authorize actors
activate chaos
activate auth
activate s1
user -> chaos : kill(token, service1)
chaos -> auth : verify(token)
auth --> chaos : Actor is authorized
chaos -> s1 : kill()
destroy s1

@enduml