//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticGTFS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticGTFS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url
        ///STM,&quot;Société de transport de Montréal&quot;,http://www.stm.info,America/Montreal,fr,,http://www.stm.info/fr/infos/titres-et-tarifs
        ///.
        /// </summary>
        internal static string agency {
            get {
                return ResourceManager.GetString("agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
        ///22U-H50U000S-82-S,1,1,1,1,1,0,0,20220613,20220819
        ///22U-H50U000S-82-SV,0,0,0,0,1,0,0,20220613,20220819
        ///22U-H54U000S-82-S,1,1,1,1,1,0,0,20220613,20220819
        ///22U-H55U000S-01-S,1,1,1,1,1,0,0,20220613,20220819
        ///22U-H55U000S-01-SV,0,0,0,0,1,0,0,20220613,20220819
        ///22U-H56U000S-80-S,1,1,1,1,1,0,0,20220613,20220819
        ///22U-H56U000S-80-SV,0,0,0,0,1,0,0,20220613,20220819
        ///22U-H57U000S-81-S,1,1,1,1,1,0,0,20220613,20220819
        ///22U-H58U000S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service_id,date,exception_type
        ///22U-H50U000S-82-S,20220624,2
        ///22U-H50U000S-82-SV,20220624,2
        ///22U-H50U000S-82-S,20220701,2
        ///22U-H50U000S-82-SV,20220701,2
        ///22S-H50S000S-81-S,20220905,2
        ///22S-H50S000S-81-S,20221010,2
        ///22U-H54U000S-82-S,20220624,2
        ///22U-H54U000S-82-S,20220701,2
        ///22S-H54S000S-81-S,20220905,2
        ///22S-H54S000S-81-S,20221010,2
        ///22U-H55U000S-01-S,20220624,2
        ///22U-H55U000S-01-SV,20220624,2
        ///22U-H55U000S-01-S,20220701,2
        ///22U-H55U000S-01-SV,20220701,2
        ///22S-H55S000S-80-S,20220905,2
        ///22S-H55S000S-80-S,20221010 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string calendar_dates {
            get {
                return ResourceManager.GetString("calendar_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fare_id,price,currency_type,payment_method,transfers,transfer_duration
        ///13S_747,10.00,CAD,0,,7200
        ///13S_REG,3.50,CAD,0,,7200
        ///.
        /// </summary>
        internal static string fare_attributes {
            get {
                return ResourceManager.GetString("fare_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fare_id,route_id,origin_id,destination_id,contains_id
        ///13S_REG,1,,,
        ///13S_REG,2,,,
        ///13S_REG,4,,,
        ///13S_REG,5,,,
        ///13S_REG,10,,,
        ///13S_REG,11,,,
        ///13S_REG,12,,,
        ///13S_REG,13,,,
        ///13S_REG,14,,,
        ///13S_REG,15,,,
        ///13S_REG,16,,,
        ///13S_REG,17,,,
        ///13S_REG,18,,,
        ///13S_REG,19,,,
        ///13S_REG,21,,,
        ///13S_REG,22,,,
        ///13S_REG,24,,,
        ///13S_REG,25,,,
        ///13S_REG,26,,,
        ///13S_REG,27,,,
        ///13S_REG,28,,,
        ///13S_REG,29,,,
        ///13S_REG,30,,,
        ///13S_REG,31,,,
        ///13S_REG,32,,,
        ///13S_REG,33,,,
        ///13S_REG,34,,,
        ///13S_REG,35,,,
        ///13S_REG,36,,,
        ///13S_REG,37,,,
        ///13S_REG,39, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fare_rules {
            get {
                return ResourceManager.GetString("fare_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed_publisher_name,feed_publisher_url,feed_lang,feed_start_date,feed_end_date
        ///&quot;Société de transport de Montréal&quot;,http://www.stm.info,fr,20220613,20221023
        ///.
        /// </summary>
        internal static string feed_info {
            get {
                return ResourceManager.GetString("feed_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route_id,agency_id,route_short_name,route_long_name,route_type,route_url,route_color,route_text_color
        ///1,STM,1,Verte,1,http://www.stm.info/fr/infos/reseaux/metro/verte,00B300,000000
        ///2,STM,2,Orange,1,http://www.stm.info/fr/infos/reseaux/metro/orange,D95700,000000
        ///4,STM,4,Jaune,1,http://www.stm.info/fr/infos/reseaux/metro/jaune,FFD900,000000
        ///5,STM,5,Bleue,1,http://www.stm.info/fr/infos/reseaux/metro/bleue,0095E6,000000
        ///10,STM,10,De Lorimier,3,http://www.stm.info/fr/infos/reseaux/bus,009EE0,
        ///11,STM,11,Par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string routes {
            get {
                return ResourceManager.GetString("routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] stop_times {
            get {
                object obj = ResourceManager.GetObject("stop_times", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_url,location_type,parent_station,wheelchair_boarding
        ///STATION_M118,10118,STATION ANGRIGNON,45.446466,-73.603118,,1,,2
        ///43,10118,Station Angrignon,45.446466,-73.603118,http://www.stm.info/fr/infos/reseaux/metro/angrignon,0,STATION_M118,2
        ///43-01,10118,Station Angrignon,45.446319,-73.603835,,2,STATION_M118,2
        ///STATION_M120,10120,STATION MONK,45.451158,-73.593242,,1,,2
        ///42,10120,Station Monk,45.451158,-73.593242,http://www.stm.info/fr/infos/reseaux/metro/monk,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stops {
            get {
                return ResourceManager.GetString("stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route_id,service_id,trip_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,note_fr,note_en
        ///4,22S-GLOBAUX-50-S,254107023,STATION BERRI-UQAM,0,40025,1,,
        ///4,22S-GLOBAUX-50-S,254107024,STATION BERRI-UQAM,0,40025,1,,
        ///4,22S-GLOBAUX-50-S,254107027,STATION LONGUEUIL–UNIVERSITÉ-DE-SHERBROOKE,1,40024,1,,
        ///4,22S-GLOBAUX-50-S,254107028,STATION LONGUEUIL–UNIVERSITÉ-DE-SHERBROOKE,1,40024,1,,
        ///4,22S-GLOBAUX-50-S,254107029,STATION LONGUEUIL–UNIVERSITÉ-DE-SHERBROOKE,1,40024,1,,
        ///4,22S-GLOBAUX-50-S,254107030,STA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trips {
            get {
                return ResourceManager.GetString("trips", resourceCulture);
            }
        }
    }
}
