@startuml RDTQ Disponbilité : Préparation et réparation

participant "Copie principale : Authentication Microservice" as main
participant "Nouvelle Copie : Authentication Microservice" as copy

note over main, copy : Tactique : State resynchronization
note over main 
Ancienne copie secondaire,
maintenant principale
end note
activate main
main -> copy : start(myPid, yourUrl)
activate copy
note over copy
Connaît maintenant les informations
de la copie principale
end note
ref over main, copy : voir Disponibilité : Détection de faute

@enduml