@startuml RDTQ Disponbilité : Prévention de fautes

actor ": Utilisateur" as user
participant ": Authentication Microservice" as auth
database ": Base de données" as db

note over user, db : Tactique : Increase competence set
activate auth
user -> auth : signUp(username, password)
auth -> auth : generateToken(username, password)
opt Connexion perdue avec la base de données
  auth -x db : save(username, password, token)
  auth -> auth : saveLocal(username, password)
  auth --> user : token
  user -> auth : login(username, password)
  auth -> auth : getLocal(username, password)
  auth --> user : token
end
opt Connexion récupérée
  loop Comptes créés mais non persistés
    auth -> db : save(username, password, token)
  end
end


@enduml