@startuml
skinparam component {
  backgroundColor<<Interne>> DarkKhaki
  backgroundColor<<Exterme>> Green
}
actor User as u
package SystemeAuthentificationMS as s {
 [Authentification_UI] as clt <<Interne>>
 [Authentification_MS] as ms <<Interne>>
    } 
 [Database] as bd <<Interne>>
 [Chaos] as k <<Interne>>
 [MS_Equipe4] as 4 <<Exterme>>
 [MS_Equipe6] as 6 <<Exterme>>
 [MS_Equipe8] as 8 <<Exterme>>
 
u   ->   s 
s  ->  bd
s  ->  4
s  ->  6
s  ->  8
clt   ->  ms 
k   ->  ms 
@enduml
