@startuml
skinparam component {
  backgroundColor<<Interne>> DarkKhaki
  backgroundColor<<Exterme>> Green
}
actor User as u

 [Authentification_UI] as ui <<Interne>>
 [Authentification_MS] as ms <<Interne>>
 [Database] as bd <<Interne>>
 [Chaos]  as ko <<Interne>> 
 () IPublic as i <<Exterme>>
 note bottom of i:IPublic est interface des equipes 4,6 et 8
u   ->  ui
ui ->  ms
ui ->  ko
ms   ->  bd 
ui   ->  i 
@enduml
