
@startuml
skinparam component {
  backgroundColor<<IMPLEMENTATION>> DarkKhaki
  backgroundColor<<Integration>> yellow
}
component Authentification-MS_Copie  as ms2 <<IMPLEMENTATION>> {
  }
component Authentification-MS_Origniale as ms1 <<IMPLEMENTATION>>{
  }
  () IserviceDiscovery as equipe4 <<Integration>> 
  () IserviceTrajet as equipe6 <<Integration>> 
 
  () IserviceMonitoring  as equipe8 <<Integration>>

  () IDatabase

[Database] as bd <<IMPLEMENTATION>>
[Chaos] as k <<IMPLEMENTATION>>

k --> ms1
k --> ms2
 ms1 ..> equipe4
 ms1 ..> equipe6
 ms1 ..> equipe8
ms1 --> IDatabase
ms2 --> IDatabase
IDatabase -- bd

@enduml
